# Generated by Django 3.2 on 2021-04-30 13:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='emp_img')),
                ('name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('doj', models.DateField(default=django.utils.timezone.now)),
                ('gender', models.CharField(max_length=6)),
                ('eval', models.CharField(default='Default', max_length=100)),
                ('insurance', models.BooleanField(default=False)),
                ('salary', models.FloatField(default=0.0)),
                ('dept', models.TextField()),
                ('remarks', models.TextField()),
            ],
        ),
    ]
