# Generated by Django 3.2 on 2021-04-28 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='emp_img')),
                ('name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('gender', models.IntegerField()),
                ('salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('dept', models.TextField()),
                ('remarks', models.TextField()),
            ],
        ),
    ]
