# Generated by Django 3.2 on 2021-04-29 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_details', '0002_alter_employee_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='eval',
            field=models.CharField(default='Default', max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(max_length=6),
        ),
    ]
