# Generated by Django 3.2 on 2021-05-01 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_details', '0005_employee_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='age',
        ),
        migrations.AddField(
            model_name='employee',
            name='beneficiaries',
            field=models.IntegerField(default=0),
        ),
    ]
