# Generated by Django 3.2 on 2021-05-01 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp_details', '0006_auto_20210501_2237'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='beneficiaries',
            new_name='dependants',
        ),
    ]
