# Generated by Django 3.2 on 2021-05-01 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_details', '0007_rename_beneficiaries_employee_dependants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='dependants',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
